#!/system/bin/sh

#-------------------------------------------
# swap file in /cache partition
#
#     ****
#   **
#   **                ****      created by
#    ***            **    **
#     * **         **     **    delta-roh
#   **    **       ** ****
#  **      **       **          in 2013
#  **     **         ****
#    ****               **
#                      **
#-------------------------------------------
# Use file in /cache partition as swap
#
# description:
# - this script creates a file on the
#   /cache partition as swap space
#
#
# version history:
#   changed    by        ver  comment
#   2013-02-02 delta-roh 1.00 release
#
version_swap_cache="V1.00"
#----------------------------------------

#----------------------------------------
# please change/adjust these params
#----------------------------------------
sub_dir="/cache/swap"
log_file_name="swap.log"
swap_file_name="swap.img"
swap_file_size_mb=50
swappiness=90

#----------------------------------------
# start of the script
#----------------------------------------
log_file=$sub_dir/$log_file_name;
swap_file=$sub_dir/$swap_file_name;
mkdir -p $sub_dir;
if [ -e $log_file ] ; then rm $log_file; fi;

echo "-------------------------------------" > $log_file;
echo "- swapfile on cache partition $version_swap_cache -" >> $log_file;
echo "- by delta-roh                      -" >> $log_file;
echo "-------------------------------------" >> $log_file;
echo "" >> $log_file;
echo ">parameters:" >> $log_file;
echo "  sub directory: " $sub_dir >> $log_file;
echo "  swap file: " $swap_file >> $log_file;
echo "  log file: " $log_file >> $log_file;
echo "  swappiness: " $swappiness >> $log_file;
echo "  swap size [MB]: " $swap_file_size_mb >> $log_file;
echo ""  >> $log_file;

if [ -e $swap_file ] ;
then
    echo "---------swapfile exists-------------" >> $log_file;
    echo ">check size of swapfile" >> $log_file;
    if [ `stat -c%s $swap_file` -eq $(($swap_file_size_mb*1024*1024)) ] ;
    then
        echo ">size not changed" >> $log_file;
    else
        echo ">size changed - delete and create" >> $log_file;
		rm $swap_file;
	fi;
else
    echo "-------swapfile does not exist-------" >> $log_file;
fi;

if [ ! -e $swap_file ] ;
then
    echo ">create swapfile" >> $log_file;
    dd if=/dev/zero of=$swap_file bs=1048576 count=$swap_file_size_mb >> $log_file;
fi;

if [ -e $swap_file ] ;
then
    echo ">create swapfile structure in file" >> $log_file;
    echo ""  >> $log_file;
    chown root.root $swap_file >> $log_file;
    chmod 0600 $swap_file >> $log_file;
    /system/xbin/mkswap $swap_file >> $log_file;

    echo "" >> $log_file;
    echo ">activate swapfile" >> $log_file;
    /system/xbin/swapon $swap_file >> $log_file;

    echo ">set swappiness=($swappiness)" >> $log_file;
    echo $swappiness > /proc/sys/vm/swappiness;

    echo "" >> $log_file;
    echo "--write infos about swapfile to log--" >> $log_file;
    echo ">result of cat /proc/swaps:" >> $log_file;
    cat /proc/swaps >> $log_file;

#   echo "" >> $log_file;
#   echo ">result of cat /proc/meminfo:" >> $log_file;
#   cat /proc/meminfo >> $log_file;
#   echo "" >> $log_file;

    echo "" >> $log_file;
    echo ">result of free:" >> $log_file;
    free >> $log_file;
else
    echo "-ERROR:creation of swapfile failed! -" >> $log_file;
    echo ""  >> $log_file;
fi;

echo "" >> $log_file;
echo "---end of swap to cache partition----" >> $log_file;
echo "" >> $log_file;
